Feat: categorypage 및 검색 API 연결
devryyeong/hand-over-frontend pull request #22
Opened 2023-05-17 13:31 UTC by eunji0

## 📍 주요 변경사항

- 검색기능 추가 및 API연결(+검색어 url에 추가)
- 카테고리 페이지 모두 추가
- 데이터 API 연결

## 💡 중점적으로 봐주었으면 하는 부분

- userToken 임시로 넣어뒀습니다!

2023-05-18 10:06 UTC, devryyeong requested changes
작업 엄청 많이 하셨네요...!! 코멘트 쓰는데 렉이 걸렸습니다 ㅋㅋㅋ 고생하셨어요!

2023-05-18 10:06 UTC, devryyeong commented on src/App.jsx
> +        {<Outlet />}
Outlet은 잘 모르는데 `<Outlet />`이 아니고 `{<Outlet />}` 이 맞나요 ???

2023-05-18 10:06 UTC, devryyeong commented on src/components/Header.jsx
> +import MyPageSrc from '../assets/svg/myPage.svg';
카멜케이스 / 파스칼케이스 둘 중 하나로 통일하는게 좋을 것 같습니다~

2023-05-18 10:06 UTC, devryyeong commented on src/pages/categoryPage/AllPage.jsx
> +	//날짜순, 가격순 나열
가격 기준 조회 api가 따로 있지 않았었나요? 근데 개인적으론 이렇게 프론트에서 처리하는게 더 낫지 않을까..싶긴 합니다

2023-05-18 16:03 UTC, eunji0 commented on src/App.jsx
> +        {<Outlet />}
네 중괄호 쓰는게 맞는 걸로 알고 있습니닷

2023-05-18 16:04 UTC, eunji0 commented on src/pages/categoryPage/AllPage.jsx
> +	//날짜순, 가격순 나열
따로 있는데 백엔드랑 상의후 프론트에서 처리하기로 했습니다!

2023-05-18 16:08 UTC, eunji0 commented on src/components/Header.jsx
> +import MyPageSrc from '../assets/svg/myPage.svg';
수정해놨습니당

2023-05-19 01:14 UTC, devryyeong approved these changes
👍

2023-05-19 01:16 UTC, merged